namespace SDRSharp.FrontEnds.SpyServer
{
	public enum SettingType : uint
	{
		SETTING_STREAMING_MODE,
		SETTING_STREAMING_ENABLED,
		SETTING_GAIN,
		SETTING_IQ_FORMAT = 100u,
		SETTING_IQ_FREQUENCY,
		SETTING_IQ_DECIMATION,
		SETTING_IQ_DIGITAL_GAIN,
		SETTING_FFT_FORMAT = 200u,
		SETTING_FFT_FREQUENCY,
		SETTING_FFT_DECIMATION,
		SETTING_FFT_DB_OFFSET,
		SETTING_FFT_DB_RANGE,
		SETTING_FFT_DISPLAY_PIXELS
	}
}
