namespace SDRSharp.FrontEnds.Airspy
{
	public enum airspy_error
	{
		AIRSPY_SUCCESS,
		AIRSPY_TRUE,
		AIRSPY_ERROR_INVALID_PARAM = -2,
		AIRSPY_ERROR_NOT_FOUND = -5,
		AIRSPY_ERROR_BUSY = -6,
		AIRSPY_ERROR_NO_MEM = -11,
		AIRSPY_ERROR_LIBUSB = -1000,
		AIRSPY_ERROR_THREAD = -1001,
		AIRSPY_ERROR_STREAMING_THREAD_ERR = -1002,
		AIRSPY_ERROR_STREAMING_STOPPED = -1003,
		AIRSPY_ERROR_OTHER = -9999
	}
}
